#pragma once
#include "stdafx.h"

void __stdcall do_effect_command(int qty, int command, void* player, UNIT** objects, int count, UNIT* target_obj, int x, int y);
const char* __stdcall get_command_name(int c);

//commands

#define RGE_COMMAND_ORDER 0x00
#define RGE_COMMAND_STOP 0x01
#define RGE_COMMAND_AI_ORDER 0x02
#define RGE_COMMAND_MOVE 0x03
#define RGE_COMMAND_AI_MOVE 0x0A
#define RGE_COMMAND_RESIGN 0x0B
#define RGE_COMMAND_WAYPOINT 0x0C
#define RGE_COMMAND_GROUP_WAYPOINT 0x10
#define RGE_COMMAND_GROUP_AI_ORDER 0x11
#define RGE_COMMAND_STANCE 0x12
#define RGE_COMMAND_GUARD 0x13
#define RGE_COMMAND_FOLLOW 0x14
#define RGE_COMMAND_PATROL 0x15
#define RGE_COMMAND_SCOUT 0x16
#define RGE_COMMAND_FORMATION 0x17
#define RGE_COMMAND_BREAK_FORMATION 0x18
#define RGE_COMMAND_WHEEL_FORMATION 0x19
#define RGE_COMMAND_ABOUT_FACE_FORMATION 0x1A
#define RGE_COMMAND_MULTIPLAYER_SAVE 0x1B
#define RGE_COMMAND_FORMATION_PARAMETERS 0x1C
#define RGE_COMMAND_AUTO_FORMATION 0x1D
#define RGE_COMMAND_LOCK_FORMATION 0x1E
#define RGE_COMMAND_GROUP_MULTI_WAYPOINTS 0x1F
#define RGE_COMMAND_CHAPTER 0x20

#define TRIBE_COMMAND_MAKE 0x64
#define TRIBE_COMMAND_RESEARCH 0x65
#define TRIBE_COMMAND_FOUNDATION 0x66
#define TRIBE_COMMAND_GAME 0x67
#define TRIBE_COMMAND_WALL 0x69
#define TRIBE_COMMAND_DELETE 0x6A
#define TRIBE_COMMAND_ATTACK_GROUND 0x6B
#define TRIBE_COMMAND_TRIBUTE 0x6C
#define TRIBE_COMMAND_REPAIR 0x6E
#define TRIBE_COMMAND_UNLOAD 0x6F
#define TRIBE_COMMAND_CONVERT 0x70
#define TRIBE_COMMAND_GATE 0x72
#define TRIBE_COMMAND_FLARE 0x73
#define TRIBE_COMMAND_LOAD 0x75
#define TRIBE_COMMAND_DIPLOMACY 0x76
#define TRIBE_COMMAND_TRAIN 0x77
#define TRIBE_COMMAND_GATHER_POINT 0x78
#define TRIBE_COMMAND_RETREAT_POINT 0x79
#define TRIBE_COMMAND_SELL 0x7A
#define TRIBE_COMMAND_BUY 0x7B
#define TRIBE_COMMAND_OFFBOARD_TRADE 0x7C
#define TRIBE_COMMAND_TRANSFORM 0x7D
#define TRIBE_COMMAND_DROP_RELIC 0x7E
#define TRIBE_COMMAND_TOWNBELL 0x7F
#define TRIBE_COMMAND_BACK_TO_WORK 0x80
